[package]
name = "peering"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "peering-node"
path = "src/main.rs"

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.0", features = ["full"] }
structopt = "0.3.25"

[build-dependencies]
tonic-build = "0.6"
